import { Outfit } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/NavBar";

import Footer from "@/components/shared/Footer";
import Banner from "@/components/shared/Bannner";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={outfit.className}>
      <body className={outfit.className}>
        <Navbar />
        <Banner />
        <main> {children}</main>
        <Footer />
      </body>
    </html>
  );
}
